### ISSUE TITLE
Add SPR to SubsplitDAG

### ISSUE THREAD

**Issue by davidrich27** [phylovi/bito#371]
[POSTPONED]
- Add SPR to SubsplitDAG
    - Args to u define an SPR: (source_subsplit, dest_subsplit, clave_to_move).
        - clave_to_move must be a subset of source_subsplit.
        - clave_to_move must be distjoint with dest_subsplit.
    - First a path between two subsplits must be established.  
        - Prefer to find the shortest path.  This can be done in O(V+E) using topological sort.
    - To perform SPR:
        - We remove the SPR clave on the path from the source_subsplit to the common_ancestor.        
        - We add the SPR clave on the path from the dest_subsplit to the common_ancestor.
    - I believe SPR could also be decomposed into a series of NNI operations.

**Comment by matsen** [comment]
There's some chance we'll want to do this down the road, but I'm going to close this for the time being because an SPR search for the whole dag is going to be $$$.
