### ISSUE TITLE
Single precision and beagle

### ISSUE THREAD

**Issue by 4ment** [phylovi/bito#378]
When I request single precision in BITO it appears that BEAGLE is initialised with double precision.
Here is what BITO logs:
```
We asked BEAGLE for: PRECISION_SINGLE VECTOR_SSE
BEAGLE gave us: PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_NONE PROCESSOR_CPU INVEVEC_STANDARD FRAMEWORK_CPU
```

**Comment by matsen** [comment]
After a discussion on Slack, we decided that we should, around here:

https://github.com/phylovi/bito/blob/main/src/engine.cpp#L29

check to see if PRECISION_SINGLE and VECTOR_SSE are both set in `beagle_preference_flags` and fail if they are set. This combination is not supported by BEAGLE right now.
