### ISSUE TITLE
Error running `make test` with conda env

### ISSUE THREAD

**Issue by jgallowa07** [phylovi/bito#391]
After running the Dockerfile for [gp-benchmarking](https://github.com/matsengrp/gp-benchmark-1-environment). I noticed that the `TEST_CASE("RootedSBNInstance: gradients") {` -> [Here](https://github.com/phylovi/bito/blob/098c1f0f278517f6b000b0d88e5cfe001948cef0/src/rooted_sbn_instance.hpp#L260)
is failing. I'm not sure if this is a known error, but in either case the `make test` command should probably be run in the [bito container](https://github.com/phylovi/bito/blob/main/Dockerfile) and/or a [workflow](https://github.com/phylovi/bito/blob/main/.github/workflows/build-with-cmake.yml) so errors like this can be caught right away.

**Comment by tanviganapathy** [comment]
Error fixed by using an ordered map for PCSPCounter which guarantees the PCSP index order (#402). Tests are updated to reflect new PCSP indexing. 

Images from issues #349 and #351 referenced in the code are updated here.

**Comment by tanviganapathy** [comment]
Showing unconditional node probabilities for `data/five_taxon.fasta`, `data/five_taxon_rooted_more_2.nwk` example:
![rooted_more_2_inked](https://user-images.githubusercontent.com/62405940/176058022-88a58645-d5b3-478b-b211-a3d38e624674.svg)

old image: https://github.com/phylovi/bito/issues/349#issuecomment-897266149

The svgs for these are in `doc/svg`.

**Comment by tanviganapathy** [comment]
`data/5-taxon-slice-of-ds1.fasta`
`data/5-taxon-only-rootward-uncertainty.nwk`

![output1](https://user-images.githubusercontent.com/62405940/176058505-6309125e-6951-42ed-a38d-4ecf2ceca650.png)

old image: https://github.com/phylovi/bito/issues/349#issuecomment-897233859

**Comment by tanviganapathy** [comment]
Adding 24|3 and 2|4 to `data/five_taxon_rooted_more_2` (https://github.com/phylovi/bito/issues/391#issuecomment-1168046752).

![Inkedoutput_parent_child_add](https://user-images.githubusercontent.com/62405940/176059193-70c32460-2b7a-4a81-9f5c-28221ae3b3f3.jpg)

old image: https://github.com/phylovi/bito/issues/351#issuecomment-908708284

**Comment by tanviganapathy** [comment]
Adding 12|34 and 1|2 to `data/five_taxon_rooted_more_2` (https://github.com/phylovi/bito/issues/391#issuecomment-1168046752). 

![Inkedoutput_prep_add](https://user-images.githubusercontent.com/62405940/176059444-710a9390-eed3-4528-8344-2019bc743bf6.jpg)

Adding 0|12 and 1|2 (just adds 0|12) to the previous DAG.

![Inkedoutput_only_parent](https://user-images.githubusercontent.com/62405940/176059492-fb58083a-da92-4698-b777-bf0446a2237e.jpg)

old image: https://github.com/phylovi/bito/issues/351#issuecomment-908709477

**Comment by tanviganapathy** [comment]
`data/five_taxon.fasta`
`data/five_taxon_rooted_more_3.nwk`

![output3](https://user-images.githubusercontent.com/62405940/176059658-9b50d32e-ed20-46ec-a2de-537e49abba66.png)

Adding 1|234 and 24|3 (just adds 24|3) to `data/five_taxon_rooted_more_3.nwk`

![Inkedoutput_only_child](https://user-images.githubusercontent.com/62405940/176059973-68b0259f-9bf6-48a1-90e0-7fb2f109506c.jpg)

old image: https://github.com/phylovi/bito/issues/351#issuecomment-908711187

**Comment by tanviganapathy** [comment]
`data/ds1-reduced-5.fasta`
`data/ds1-reduced-5.nwk`

![output_ds1_5](https://user-images.githubusercontent.com/62405940/176250916-db1b34fd-1d53-48b8-a878-a8f7ba0434b8.png)

old image: https://github.com/phylovi/bito/issues/349#issuecomment-897924835
