### ISSUE TITLE
Store edge ids with neighboring nodes

### ISSUE THREAD

**Issue by ognian-** [phylovi/bito#403]
In SubsplitDAGNode add edge ids to the lists of neighbor node ids.

**Comment by matsen** [comment]
@ognian- my understanding is that this actually

* replaces the vector of neighbor node ids with an unordered map that goes to the edge id
* adds a vector indexed by edge ids to node id pairs. 

Is that correct?

**Comment by ognian-** [comment]
Yes, but in an elaborate way that uses the internal storage data structure that we discussed.
