### ISSUE TITLE
Function for duplicating trees

### ISSUE THREAD

**Issue by 4ment** [phylovi/bito#408]
It would be nice to be able to duplicate tree(s) loaded in BITO.

For example, since torchtree makes BITO load a single topology it cannot do multithreading. With a multisample ELBO torchtree currently calculates the K gradients one after another.

We could have a `DuplicateTree(size K)` function in `GenericSBNInstance`. It has a similar function for model parameters: `ResizePhyloModelParams`

**Comment by matsen** [comment]
My proposal is to make a function `LoadDuplicatesOfFirstTree` that will replace all of the loaded trees with duplicates of the first tree. Seem good?

**Comment by 4ment** [comment]
sounds good
