### ISSUE TITLE
Tweaks to enable GP work

### ISSUE THREAD

**Issue by matsen** [phylovi/bito#413]
From @junseonghwan :

1. Currently, GP is lacking a feature to retrieve the branch lengths programmatically via pybito. The workaround that I have been using is to output the branch lengths and PCSPs to CSV and then reading it in from Python. Ideally, I would like to retrieve GP branch lengths from python in similarly to GatherBranchLengths — but instead of returning (index, vector<double>) map, (index, double) map.
2.To deal with the branch length estimates involving the outgroup (rootsplit), we will need to ask if a PCSP is a rootsplit.

**Comment by matsen** [comment]
Regarding your second need, it seems to me that because (I think/hope) you are rerooting on the outgroup, the rootsplit should always be subsplit index 0 (top of the tree).

So, to rephrase your question, you'd like to know all of the PCSP (i.e. DAG edge) indices that emerge from node 0. There is a subsplit DAG function called `PrintDAGEdges` which gives all of the parent, child ID pairs. It seems to me that this should theoretically satisfy your request, but we'd want to make it more accessible from Python. Do you agree?

**Comment by junseonghwan** [comment]
```
Regarding your second need, it seems to me that because (I think/hope) you are rerooting on the outgroup, the rootsplit should always be subsplit index 0 (top of the tree).
```

Yes, I am rerooting on the outgroup. I can look up the rootsplits by checking if the PCSP starts with a binary string that looks like 10...0|01...1 or 01...1|10...0.

We probably don't need to implement the second feature.

**Comment by davidrich27** [comment]
Okay, I added `get_branch_lengths_map` and `get_rootsplit_edge_idxs` to pybito.  Usage example is in `test_gp_instance` function in `test/test_bito.py`.  @junseonghwan let me know if that's what you were wanting.

**Comment by junseonghwan** [comment]
`get_branch_lengths_map` is exactly what I wanted. 

`get_rootsplit_edge_idxs` returns the index of the artificial rootsplit. Since I have an outgroup, I'm always getting 0 as @matsen mentioned above. The indices that I want to get are one level lower, the children of the rootsplit. 

As I mentioned above, this function is probably not necessary anymore... I would like to filter through PCSPs for from Python, so exposing a function that returns a map from the index to PCSP might be helpful instead.

**Comment by davidrich27** [comment]
Okay, I've updated the branch with `get_edge_idx_to_pcsp_map`.  Does this look good?
