### ISSUE TITLE
Top-Pruning, pt. 1: Choice Maps on SubsplitDAG

### ISSUE THREAD

**Issue by davidrich27** [phylovi/bito#442]
For our first step in implementing top-pruning into Bito and the NNI Engine, we are building a choice map on the SubsplitDAG.  The choice map with be a helper for tracking and extracting the best tree from the SubsplitDAG containing a given PCSP.  I believe that this could be as simple as per-edge struct containing the four adjacent node ids (parent, sister, left_child, right_child)?  Maybe we want to store the likelihood of the associated best tree as well for quick comparison?

**Comment by matsen** [comment]
@davidrich27 

* do we want to store a leafward choice map and a rootward choice map separately? seems like advantages and disadvantages for each. 
* interesting idea about storing likelihood. I'd like for this to be "score" so we could store parsimony as well. But perhaps not for this scope of work?

Can you describe the endpoint for the corresponding PR? Are we going to be able to build a tree from the choice maps? Will there be tests?

**Comment by matsen** [comment]
Re two maps vs one, let's go for one-- keep things simple. 

It sounds like we'll be storing our parsimony score (int) as a double, but I'll chill about this. 

Perhaps a more interesting/important generalization is: what if we stored multiple choices in a single entry? This would allow us to keep track of several different options and how good they are. 

Hopefully this is clear-- let me know if not.

tagging @chrisjenningsshaffer for further discussion. What's interesting is this is starting to feel SBN-ish, but not really... these maps go up as well as down.

**Comment by davidrich27** [comment]
Are you thinking there should be a constant number of these alternatives, or do you want to resizeable number of alternatives per edge?

**Comment by matsen** [comment]
I was thinking resizable, yes.
