### ISSUE TITLE
TPEngine: Move PVs from Node-based to Edge-based

### ISSUE THREAD

**Issue by davidrich27** [phylovi/bito#465]
Currently, the Partial Vectors for the TPEngines are stored on the nodes of the DAG.  When we are computing the PV for a given node, on the rootward pass, this is examining the edges whose parent is the current node.  On the leafward pass, this is examining the edges whose child is the current node.  For the node-based PV implementation, we are choosing the edge that comes from the best likelihood/parsimony tree from the collection which the DAG was constructed.  From there, we use that edge's choice map for determining its left_child, right_child, sister, and parent edges.  But this can mean that an edge likelihood/parsimony may end up using node PV from a different tree in its computation.

Instead we are moving to storing the PVs on the edges.  This means we can skip the "choose the edge from the best tree" step, and simply iteratively compute all edge PVs that contain the node as a parent (on the rootward pass) or child (on the leafward pass).  From there, all other computations should be able to continue as usual.  This means that an edge p-PV will store the likelihood after evolving down to that edge's child, and an edge r-PV will store the likelihood after evolving up to that edge's parent.

**Comment by chrisjenningsshaffer** [comment]
This looks right to me. It is a little hard to wrap my head around the details. To double check, is this an example of the current issue and what your changes will fix?

Under the current implementation, the node (1|234) uses PVs that correspond to Tree 1.
For the edge (1|234)->(24|3), the likelihood is computed with the parent edge (1234|5)->(1|234), but it should instead use the edge (0|1234)->(1|234).

[edges_nodes.pdf](https://github.com/phylovi/bito/files/9529824/edges_nodes.pdf)

**Comment by davidrich27** [comment]
Yes, that is correct.  Thanks for the clarifying example.
